import type { ExperienceItem } from '@/app/experience/_components/ExperienceCardGrid';

export const experienceMockData: ExperienceItem[] = [
  {
    id: 'experience-1',
    type: 'etc',
    title: '고가용성 결제 시스템 설계 및 운영',
    period: '2026.04.01~04.28',
    skillTags: ['Chrome Extension', 'Multi-Variate Testing'],
    competencyTags: ['역량', '역량'],
  },
  {
    id: 'experience-2',
    type: 'education',
    title: '고가용성 결제 시스템 설계 및 운영',
    period: '2026.04.01~04.28',
    skillTags: ['기술', '기술'],
    competencyTags: ['역량', '역량'],
  },
  {
    id: 'experience-3',
    type: 'activity',
    title: '고가용성 결제 시스템 설계 및 운영',
    period: '2026.04.01~04.28',
    skillTags: ['기술', '기술'],
    competencyTags: ['역량', '역량'],
  },
  {
    id: 'experience-4',
    type: 'career',
    title: '고가용성 결제 시스템 설계 및 운영',
    period: '2026.04.01~04.28',
    skillTags: ['기술', '기술'],
    competencyTags: ['역량', '역량'],
  },
  {
    id: 'experience-5',
    type: 'etc',
    title: '고가용성 결제 시스템 설계 및 운영',
    period: '2026.04.01~04.28',
    skillTags: ['기술', '기술'],
    competencyTags: ['역량', '역량'],
  },
  {
    id: 'experience-6',
    type: 'education',
    title: '고가용성 결제 시스템 설계 및 운영',
    period: '2026.04.01~04.28',
    skillTags: ['기술', '기술'],
    competencyTags: ['역량', '역량'],
  },
  {
    id: 'experience-7',
    type: 'activity',
    title: '고가용성 결제 시스템 설계 및 운영',
    period: '2026.04.01~04.28',
    skillTags: ['기술', '기술'],
    competencyTags: ['역량', '역량'],
  },
  {
    id: 'experience-8',
    type: 'career',
    title: '고가용성 결제 시스템 설계 및 운영',
    period: '2026.04.01~04.28',
    skillTags: ['기술', '기술'],
    competencyTags: ['역량', '역량'],
  },
  {
    id: 'experience-9',
    type: 'etc',
    title: '고가용성 결제 시스템 설계 및 운영',
    period: '2026.04.01~04.28',
    skillTags: ['기술', '기술'],
    competencyTags: ['역량', '역량'],
  },
  {
    id: 'experience-10',
    type: 'education',
    title: '고가용성 결제 시스템 설계 및 운영',
    period: '2026.04.01~04.28',
    skillTags: ['기술', '기술'],
    competencyTags: ['역량', '역량'],
  },
  {
    id: 'experience-11',
    type: 'activity',
    title: '고가용성 결제 시스템 설계 및 운영',
    period: '2026.04.01~04.28',
    skillTags: ['기술', '기술'],
    competencyTags: ['역량', '역량'],
  },
  {
    id: 'experience-12',
    type: 'career',
    title: '고가용성 결제 시스템 설계 및 운영',
    period: '2026.04.01~04.28',
    skillTags: ['기술', '기술'],
    competencyTags: ['역량', '역량'],
  },
];
