import type { ExperienceItem } from '@/app/experience/_components/ExperienceCardGrid';
import type { ExperienceCategory } from '@/app/experience/_components/ExperienceCategoryTab';

type ExperienceType = Exclude<ExperienceCategory, 'all'>;

const defaultExperienceDetail = {
  description: '복잡한 비즈니스 로직을 DDD 패턴으로 설계하여 유지보수성 향상',
  detail: {
    situation: '기존 서비스는 결제 도메인의 정책과 예외 처리가 여러 계층에 흩어져 있어 변경 영향 범위를 예측하기 어려웠습니다.',
    task: '결제 정책을 명확한 도메인 모델로 분리하고, 추후 기능 확장 시에도 유지보수하기 쉬운 구조를 설계해야 했습니다.',
    action: '도메인 이벤트와 애그리거트 기준으로 책임을 나누고, 결제 상태 전이를 명시적으로 관리할 수 있도록 모델을 재구성했습니다.',
    result: '결제 정책 변경 시 수정 지점이 줄어들었고, 주요 플로우에 대한 테스트 작성 범위도 명확해졌습니다.',
    taken: '복잡한 비즈니스 로직은 UI나 인프라보다 도메인 규칙을 먼저 정리해야 장기적인 변경 비용을 줄일 수 있다는 점을 배웠습니다.',
  },
} satisfies Pick<ExperienceItem, 'description' | 'detail'>;

const detailInfoMap = {
  activity: [
    { label: '기간', value: '2026.04.01~04.28' },
    { label: '팀원 수', value: '1인' },
    { label: '내 역할 및 기여도', value: '팀장, 100%' },
  ],
  career: [
    { label: '기간', value: '2026.04.01~04.28' },
    { label: '회사/기관/단체명', value: '리트머스' },
    { label: '고용 형태', value: '인턴' },
  ],
  education: [
    { label: '기간', value: '2026.04.01~04.28' },
    { label: '기관명', value: '큐시즘대학교' },
    { label: '수강명', value: '데이터베이스시스템' },
  ],
  etc: [{ label: '기간', value: '2026.04.01~04.28' }],
} satisfies Record<ExperienceType, ExperienceItem['detailInfo']>;

export const experienceMockData: ExperienceItem[] = [
  {
    id: 'experience-1',
    type: 'etc',
    title: '고가용성 결제 시스템 설계 및 운영',
    period: '2026.04.01~04.28',
    ...defaultExperienceDetail,
    detailInfo: detailInfoMap.etc,
    skillTags: ['Chrome Extension', 'Multi-Variate Testing'],
    competencyTags: ['역량', '역량'],
  },
  {
    id: 'experience-2',
    type: 'education',
    title: '고가용성 결제 시스템 설계 및 운영',
    period: '2026.04.01~04.28',
    ...defaultExperienceDetail,
    detailInfo: detailInfoMap.education,
    skillTags: ['기술', '기술'],
    competencyTags: ['역량', '역량'],
  },
  {
    id: 'experience-3',
    type: 'activity',
    title: '고가용성 결제 시스템 설계 및 운영',
    period: '2026.04.01~04.28',
    ...defaultExperienceDetail,
    detailInfo: detailInfoMap.activity,
    skillTags: ['기술', '기술'],
    competencyTags: ['역량', '역량'],
  },
  {
    id: 'experience-4',
    type: 'career',
    title: '고가용성 결제 시스템 설계 및 운영',
    period: '2026.04.01~04.28',
    ...defaultExperienceDetail,
    detailInfo: detailInfoMap.career,
    skillTags: ['기술', '기술'],
    competencyTags: ['역량', '역량'],
  },
  {
    id: 'experience-5',
    type: 'etc',
    title: '고가용성 결제 시스템 설계 및 운영',
    period: '2026.04.01~04.28',
    ...defaultExperienceDetail,
    detailInfo: detailInfoMap.etc,
    skillTags: ['기술', '기술'],
    competencyTags: ['역량', '역량'],
  },
  {
    id: 'experience-6',
    type: 'education',
    title: '고가용성 결제 시스템 설계 및 운영',
    period: '2026.04.01~04.28',
    ...defaultExperienceDetail,
    detailInfo: detailInfoMap.education,
    skillTags: ['기술', '기술'],
    competencyTags: ['역량', '역량'],
  },
  {
    id: 'experience-7',
    type: 'activity',
    title: '고가용성 결제 시스템 설계 및 운영',
    period: '2026.04.01~04.28',
    ...defaultExperienceDetail,
    detailInfo: detailInfoMap.activity,
    skillTags: ['기술', '기술'],
    competencyTags: ['역량', '역량'],
  },
  {
    id: 'experience-8',
    type: 'career',
    title: '고가용성 결제 시스템 설계 및 운영',
    period: '2026.04.01~04.28',
    ...defaultExperienceDetail,
    detailInfo: detailInfoMap.career,
    skillTags: ['기술', '기술'],
    competencyTags: ['역량', '역량'],
  },
  {
    id: 'experience-9',
    type: 'etc',
    title: '고가용성 결제 시스템 설계 및 운영',
    period: '2026.04.01~04.28',
    ...defaultExperienceDetail,
    detailInfo: detailInfoMap.etc,
    skillTags: ['기술', '기술'],
    competencyTags: ['역량', '역량'],
  },
  {
    id: 'experience-10',
    type: 'education',
    title: '고가용성 결제 시스템 설계 및 운영',
    period: '2026.04.01~04.28',
    ...defaultExperienceDetail,
    detailInfo: detailInfoMap.education,
    skillTags: ['기술', '기술'],
    competencyTags: ['역량', '역량'],
  },
  {
    id: 'experience-11',
    type: 'activity',
    title: '고가용성 결제 시스템 설계 및 운영',
    period: '2026.04.01~04.28',
    ...defaultExperienceDetail,
    detailInfo: detailInfoMap.activity,
    skillTags: ['기술', '기술'],
    competencyTags: ['역량', '역량'],
  },
  {
    id: 'experience-12',
    type: 'career',
    title: '고가용성 결제 시스템 설계 및 운영',
    period: '2026.04.01~04.28',
    ...defaultExperienceDetail,
    detailInfo: detailInfoMap.career,
    skillTags: ['기술', '기술'],
    competencyTags: ['역량', '역량'],
  },
];
