import type { Metadata } from 'next';
import localFont from 'next/font/local';
import './globals.css';

const nanumSquare = localFont({
  src: [
    {
      path: '../assets/fonts/NanumSquareL.ttf',
      weight: '300',
      style: 'normal',
    },
    {
      path: '../assets/fonts/NanumSquareR.ttf',
      weight: '400',
      style: 'normal',
    },
    {
      path: '../assets/fonts/NanumSquareB.ttf',
      weight: '700',
      style: 'normal',
    },
    {
      path: '../assets/fonts/NanumSquareEB.ttf',
      weight: '800',
      style: 'normal',
    },
  ],
  display: 'swap',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko" className={`${nanumSquare.className} h-full antialiased`}>
      <body className="flex min-h-full flex-col">{children}</body>
    </html>
  );
}
