export const APPLY_RESIZE_MIN_LEFT_WIDTH = 453;
export const APPLY_RESIZE_MIN_RIGHT_WIDTH = 492;
export const APPLY_RESIZE_HANDLE_WIDTH = 10;
export const APPLY_RESIZE_PANEL_INSET = 36;
export const APPLY_RESIZE_MIN_CONTAINER_WIDTH =
  APPLY_RESIZE_MIN_LEFT_WIDTH + APPLY_RESIZE_MIN_RIGHT_WIDTH + APPLY_RESIZE_HANDLE_WIDTH;
