export const RESIZABLE_SPLIT_MIN_LEFT_WIDTH = 453;
export const RESIZABLE_SPLIT_MIN_RIGHT_WIDTH = 492;
export const RESIZABLE_SPLIT_HANDLE_WIDTH = 10;
export const RESIZABLE_SPLIT_PANEL_INSET = 36;
export const RESIZABLE_SPLIT_MIN_CONTAINER_WIDTH =
  RESIZABLE_SPLIT_MIN_LEFT_WIDTH +
  RESIZABLE_SPLIT_MIN_RIGHT_WIDTH +
  RESIZABLE_SPLIT_HANDLE_WIDTH;
export const RESIZABLE_SPLIT_MIN_HEIGHT = 873;

export const APPLY_COVER_LETTER_SPLIT_MIN_LEFT_WIDTH = 540;
export const APPLY_COVER_LETTER_SPLIT_MIN_RIGHT_WIDTH = 530;
