name: Merge to Main

on:
  schedule:
    - cron: '0 15 * * *'

permissions:
  contents: write

jobs:
  merge-to-main:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}
          ref: main  

      - name: Merge dev into main
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          git fetch origin

          git merge origin/dev --no-ff --no-edit -m "chore: main 최신화[scheduled]"

          git push origin main
